// <auto-generated />
using System;
using Intense_HR_Platform.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Intense_HR_Platform.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260511073414_OnModelCreatingChanged")]
    partial class OnModelCreatingChanged
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Intense_HR_Platform.Models.JobCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("JobCandidates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNo = "+381655525711",
                            DateOfBirth = new DateTime(2002, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "eraknikola1@gmail.com",
                            FullName = "Nikola Erak"
                        },
                        new
                        {
                            Id = 2,
                            ContactNo = "+381643828232",
                            DateOfBirth = new DateTime(1997, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "markoerak97@gmail.com",
                            FullName = "Marko Erak"
                        },
                        new
                        {
                            Id = 3,
                            ContactNo = "+381605827127",
                            DateOfBirth = new DateTime(2002, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mikipol14@gmail.com",
                            FullName = "Milan Polić"
                        },
                        new
                        {
                            Id = 4,
                            ContactNo = "+381601593250",
                            DateOfBirth = new DateTime(2001, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "markomarkovic@gmail.com",
                            FullName = "Marko Marković"
                        },
                        new
                        {
                            Id = 5,
                            ContactNo = "381655525600",
                            DateOfBirth = new DateTime(2004, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "petrovicpetar@gmail.com",
                            FullName = "Petar Petrović"
                        });
                });

            modelBuilder.Entity("Intense_HR_Platform.Models.JobCandidateSkill", b =>
                {
                    b.Property<int>("JobCandidateId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("JobCandidateId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobCandidatesSkills");

                    b.HasData(
                        new
                        {
                            JobCandidateId = 1,
                            SkillId = 1
                        },
                        new
                        {
                            JobCandidateId = 1,
                            SkillId = 2
                        },
                        new
                        {
                            JobCandidateId = 1,
                            SkillId = 4
                        },
                        new
                        {
                            JobCandidateId = 1,
                            SkillId = 5
                        },
                        new
                        {
                            JobCandidateId = 2,
                            SkillId = 3
                        },
                        new
                        {
                            JobCandidateId = 2,
                            SkillId = 5
                        },
                        new
                        {
                            JobCandidateId = 3,
                            SkillId = 3
                        },
                        new
                        {
                            JobCandidateId = 3,
                            SkillId = 5
                        },
                        new
                        {
                            JobCandidateId = 4,
                            SkillId = 5
                        },
                        new
                        {
                            JobCandidateId = 4,
                            SkillId = 6
                        },
                        new
                        {
                            JobCandidateId = 5,
                            SkillId = 6
                        });
                });

            modelBuilder.Entity("Intense_HR_Platform.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "c#"
                        },
                        new
                        {
                            Id = 2,
                            Name = "java"
                        },
                        new
                        {
                            Id = 3,
                            Name = "c++"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Database design"
                        },
                        new
                        {
                            Id = 5,
                            Name = "English language"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Russian language"
                        });
                });

            modelBuilder.Entity("Intense_HR_Platform.Models.JobCandidateSkill", b =>
                {
                    b.HasOne("Intense_HR_Platform.Models.JobCandidate", null)
                        .WithMany()
                        .HasForeignKey("JobCandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Intense_HR_Platform.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
